[package]
name = "unpak"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/unpak"
description = "a no-nonsense unreal pak parsing crate"
license = "MIT OR Apache-2.0"
keywords = ["modding", "parsing"]
categories = ["filesystem", "parser-implementations"]
version = "0.4.2"
edition = "2021"

[features]
rayon = ["dep:rayon"]

[dependencies]
byteorder = "1.4"
strum = { version = "0.24", features = ["derive"] }
aes = "0.8"
flate2 = "1.0"
base64 = "0.21"
hashbrown = "0.13"
thiserror = "1.0"
rayon = { version = "1.6", optional = true }

[[example]]
name = "unpack"
required-features = ["rayon"]

[[example]]
name = "list"
required-features = ["rayon"]
